### ISSUE TITLE
Roadmap do site

### ISSUE THREAD

**Issue by nandomoreirame** [nuxtjsbrasil/nuxtjsbrasil.github.io#1]
Abrindo a primeiro Issue para discução do roadmap do site para a comunidade

**Comment by robsontenorio** [comment]
Bem, quais seriam as features básicas/mais importantes que o maravilhoso site NuxtBrasil teria? 

Ou “simplesmente” é um blog?

Voto por começar mais simples, depois evoluir. Ou seja, um blog. De preferência usando alguma ferramenta própria pra isso. Alguém falou Nuxpress.

**Comment by matvaleriano** [comment]
Concordo com a ideia de um "mvp". Vamos usar algo pra fazer os wireframes? Se sim... o que seria?

**Comment by robsontenorio** [comment]
Não tenho experiência prática com wireframes. Mas, considerando que o mvp seria o blog, o que importaria depois somente seria um “tema/template” legal. 

Logo, creio que deveríamos focar no motor do blog. A ferramenta.

**Comment by nandomoreirame** [comment]
Acho que mais simples seria institucional primeiro, depois vem o blog.

Eu penso em:

- About (Sobre a comunidade)
- Team/Membros (algo como em [PHPPR](https://phppr.org/) e [GuruPR](http://www.gurupr.org/))
- Blog/Arigos sobre Nuxtjs
- Projects (lista de projetos da comunidade)

Não necessariamente nessa ordem 😄

**Comment by galvez** [comment]
Alguém faz uma lista de 3 ou 4 exemplos de sites de comunidade legais?

**Comment by galvez** [comment]
Só pra deixar claro, eu disse "legais" no sentido de ser "da hora", bacana,
canavial de top etc :D

**Comment by nandomoreirame** [comment]
@galvez os termos "legais", "da hora", "bacana" e "canavial de top" pra quem? é bem clichê mas, vai sempre depender dos olhos que vê, tu não curiu os dois que mandei ai? eu vou mandar mais... não que eles não sejam "canavial de top", é sempre bom ter inspirações independente de feio ou bonito.

lá vai:

**Trainig Center**
> Github: https://github.com/training-center
> Site: https://trainingcenter.io

**Brasil JS**
> Site: https://braziljs.org/
> Github: https://github.com/braziljs

**Vuejs Brasil**
> Github: https://github.com/vuejs-br
> Site: https://vuejs-brasil.com.br

**Back-end Brasil**
> Github: https://github.com/backend-br
> Site: http://backendbrasil.com.br

**Python Brasil**
> Github: https://github.com/pythonbrasil
> Site: https://python.org.br

**WP Brasil**
> Site: http://wp-brasil.org/

**Zabbix Brasil**
> Site: http://zabbixbrasil.org/

**Comment by nandomoreirame** [comment]
Tem também:

**PHP DF**
> https://phpdf.org.br/

**PHP SP**
> https://phpsp.org.br/

**PHP MG**
> http://phpmg.com/

**PHPeste**
> https://phpeste.net/

**PHP Com Rapadura**
> http://phpcomrapadura.org/

**PHP RS**
> http://www.phprs.com.br/

**RoR Brasil**
> https://rubyonrailsbrasil.com.br/

**Python Brasil**
> https://python.org.br/comunidades-locais/

**Python Club**
> http://pythonclub.com.br/

**Angular Brasil**
> http://angularjsbrasil.com.br/

**Dojo CE**
> http://dojo-ce.github.io/hello-world/

**GoRails**
> http://www.gorails.com.br/

**Comment by nandomoreirame** [comment]
E tem mais!

**Node Brasil**
> http://nodebr.com/

---

Tem alguns sites de eventos tbm, que acho mó dahora:

**Front in Campinas**
> https://frontincampinas.com.br/

**Floripa JS**
> http://floripajs.org/

**Comment by robsontenorio** [comment]
Bem, com tantas opções agora fiquei indeciso!

**Comment by matvaleriano** [comment]
achei o do floripajs e o do frontincapinas os mais massas

**Comment by kavalcante** [comment]
Tenho a mesma opinião que o @mathvaleriano, acredito que devemos ser simples. Sobre o "blog", também acho uma excelente ideia. Porém, talvez possa ser algo mais como um "awesome nuxt". Com coletâneas de posts sobre nuxt, em inglês e em português.

**Comment by matvaleriano** [comment]
Irado @kavalcante

**Comment by nandomoreirame** [comment]
Acredito que vcs estejam falando do design dos sites e não do roadmap galeres, a gente precisa pensar em quais funcionalidades o site vai ter, pra mapear a  arquitetura da informação e depois o design... 

o design é o de menos, dexa comigo... vamos retroceder um pouco e pensar na estrutura belez? dai criamos uma issue pra cada item 👍

**Comment by robsontenorio** [comment]
Meu voto é por ser um blog powered por alguma ferramenta que gere estaticamente o conteúdo. Tipo nuxpress. 

Depois de um consenso sobre isso. Decidimos o conteúdo do blog. Os artigos podem ser gerenciados via PR. 

Por fim, alguém bom de desenho, bola um layout legal.

**Comment by nandomoreirame** [comment]
@robsontenorio eu não entendi bem o seu voto. vc votou para o site só ter blog e não ter as demais páginas?

**Comment by matvaleriano** [comment]
eu entendi que esse seria o mvp

**Comment by nandomoreirame** [comment]
**MVP** _(Minimum Viable Product)_ seria algo simples, pequeno e rápido, sem muito perfeccionismo, com poucas features... apenas o necessário.

No momento eu votaria pra gente fazer uma página institucional apenas falando sobre a comunidade, listando os projetos, ideias e membros. Algo que daria pra gente fazer em poucas semanas, e pensar no Blog depois, e outras features também.

**Comment by kavalcante** [comment]
Mas então galera, qual conclusão chegamos? Vamos bater o martelo para construir logo o layout do site.

**Comment by nandomoreirame** [comment]
creio que sim @kavalcante ... quem tiver ideias podem mandar na issue #3 👍

**Comment by robsontenorio** [comment]
Na minha opinião não tem muito o que prolongar nesta discussão. Acho mais eficiente alguém construir a fundação do site/blog (usando alguma ferramenta) e outras pessoas colaboram ao redor.

Neste início é mais fácil ter a fundação pronta para que os outros colaboradores trabalhem.

**Comment by kavalcante** [comment]
@robsontenorio o @nandomoreirame já deu o start na aplicação. Agora sobre o visual, não faço ideia do que seguirmos, mas vamos mover a discussão de layout para a #3

**Comment by nandomoreirame** [comment]
Bom pessoal, acho que podemos desenvolver:

**MVP - Instuticional**
- [ ] Sobre a comunidade
- [ ] Membros

**Pós MVP**
- [ ] Blog - Artigos da comunidade
- [ ] Projetos

Todos de acordo?

**Comment by nandomoreirame** [comment]
Vamos votar no Preprocessador?

1️⃣ para CSS Puro
2️⃣ para SASS
3️⃣ para Stylus
4️⃣ para outro

Valendo!! 🏃

**Comment by kavalcante** [comment]
@nandomoreirame Por mim ok!

Meu voto:  2️⃣

**Comment by nandomoreirame** [comment]
No Telegram tivemos 2 votos :two: e 3 votos :three: 
.. então faremos com Stylus 🎉

**Comment by nandomoreirame** [comment]
fechando a issue.
