### ISSUE TITLE
Domínio do site

### ISSUE THREAD

**Issue by nandomoreirame** [nuxtjsbrasil/nuxtjsbrasil.github.io#2]
Time, vamos levantar a questão do domínio?

Vale a pena comprar um domíno? (o domínio nuxt.com.br está disponível)
Ou
Deixemos o site no github.io mesmo?

---

PS. Tem a opção de hospedar e usar o subdomínio do netlify.com também 😄

**Comment by galvez** [comment]
Acabei de registrar o nuxt.com.br 👍

**Comment by nandomoreirame** [comment]
Show! 🎉

**Comment by nandomoreirame** [comment]
Done.
