### ISSUE TITLE
Espaço para vagas

### ISSUE THREAD

**Issue by matvaleriano** [nuxtjsbrasil/nuxtjsbrasil.github.io#4]
O github do react-brasil tem um projeto especifico para cadastrarem vagas... assim como o frontendbr. Seria uma boa a gente colocar algo do tipo no site ou criar um repositorio seria uma boa? Pq olhei no vue brasil e nao tem nada do tipo.

**Comment by nandomoreirame** [comment]
Acho que Nuxtjs é um nicho bem específico @mathvaleriano ... qualquer necessidade de vagas para front-end (vue, nuxt, react, etc) pode ser centralizada no FrontendBR não?

**Comment by nandomoreirame** [comment]
Digo isso pq nunca vi uma vaga procurando desenvolvedor Nuxt... já vi empresa procurando dev vuejs, react e/ou javascript puro...

**Comment by matvaleriano** [comment]
Olhando por esse lado... faz sentido. Mas no caso seria pra devs vue mesmo. Mas como vc mesmo disse... pode ser centralizado no frontendBR. 
Vou fechar a issue ;)
