### ISSUE TITLE
Hospedagem - netlify vs gh-pages

### ISSUE THREAD

**Issue by nandomoreirame** [nuxtjsbrasil/nuxtjsbrasil.github.io#6]
Vamos escolher a hospedagem?

- [ ] gh-pages
- [x] [netlify.com](http://netlify.com/)

que comecem os votos! :+1:

**Comment by kavalcante** [comment]
Por mim tanto faz, acho os dois excelentes. Porém, por praticidade, iria de gh-pages.

**Comment by matvaleriano** [comment]
concordo com a questao praticidade kkkk gh +1

**Comment by nandomoreirame** [comment]
vcs já usaram Netlify? kkk de praticidade o netlify da de 10 a 0  no gh-pages 😺

**Comment by muniz95** [comment]
Não sei se rola de subir um projeto em Nuxt no gh-pages (provavelmente não). Então eu voto no netlify ou now.sh.

**Comment by kavalcante** [comment]
@nandomoreirame  Eu uso netlify em projetos pessoais e na empresa. Concordo quando se diz respeito a CDN e alguns outros detalhes. Porém, projetos Open Source, GH é dois clicks.

@muniz95 Acredito que iremos gerar estáticos. Por isso GH pages.

**Comment by nandomoreirame** [comment]
o netlify e o gh-pages são para sites estáticos, usaremos o Nuxt build para gerar os arquivos...

**Comment by nandomoreirame** [comment]
@kavalcante para hospedar no gh-pages precisaremos de um CI como o Travis para fazer o build ou rodar testes, com o Netlify não precisamos :)

**Comment by nandomoreirame** [comment]
Subir manualmente será inviável, mas nada nos impede de usar o travisci para o build 😄

**Comment by nandomoreirame** [comment]
outro ponto positivo para o Netlify é que ele é bem mais rápido para subir um container e fazer o build do que o Travis, eu acho bem demorado para o Travis subir um container

**Comment by kavalcante** [comment]
Pensando por esse lado, tem razão.

**Comment by nandomoreirame** [comment]
fechando essa issue.
vamos usar o Netlify por enquanto, se alguém tem alguma objeção podemos discutir mais 👍
